<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModelService.Application\ModelService.Application.csproj" />
    <ProjectReference Include="..\ModelService.Domain\ModelService.Domain.csproj" />
    <ProjectReference Include="..\ModelService.Persistence\ModelService.Persistence.csproj" />
    <ProjectReference Include="..\..\PracticeService\PracticeService.Application\PracticeService.Application.csproj" />
    <ProjectReference Include="..\..\PracticeService\PracticeService.Domain\PracticeService.Domain.csproj" />
  </ItemGroup>
</Project>
