<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PracticeService.Application\PracticeService.Application.csproj" />
    <ProjectReference Include="..\PracticeService.Domain\PracticeService.Domain.csproj" />
  </ItemGroup>
</Project>
