<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><PackageReference Include="MediatR" Version="12.5.0" /><ProjectReference Include="..\CreditService.Application\CreditService.Application.csproj" /><ProjectReference Include="..\CreditService.Persistence\CreditService.Persistence.csproj" /></ItemGroup></Project>
