using CreditService.Application;
using CreditService.Domain;
using CreditService.Persistence;
using MediatR;
using Microsoft.AspNetCore.Diagnostics;

var builder=WebApplication.CreateBuilder(args);builder.Logging.ClearProviders();builder.Logging.AddConsole();builder.Services.Configure<Microsoft.AspNetCore.Routing.RouteHandlerOptions>(x=>x.ThrowOnBadRequest=true);builder.Services.AddMediatR(x=>x.RegisterServicesFromAssembly(typeof(CreditHandlers).Assembly));builder.Services.AddCreditPersistence(builder.Configuration);
var gatewayKey=builder.Configuration["Gateway:ServiceKey"]??throw new InvalidOperationException("Gateway:ServiceKey must be configured.");var provider=builder.Configuration["CreditStore:Provider"]??"MySQL";
var app=builder.Build();if(!string.Equals(provider,"Memory",StringComparison.OrdinalIgnoreCase))app.Services.GetRequiredService<CreditDatabase>().EnsureCreated();
app.Use(async(c,next)=>{var id=c.Request.Headers["X-Correlation-Id"].FirstOrDefault();c.TraceIdentifier=string.IsNullOrWhiteSpace(id)?Guid.NewGuid().ToString("N"):id;c.Response.Headers["X-Correlation-Id"]=c.TraceIdentifier;await next();});
app.UseExceptionHandler(h=>h.Run(async c=>{var ex=c.Features.Get<IExceptionHandlerFeature>()?.Error;if(ex is CreditDomainException d){c.Response.StatusCode=d.StatusCode;await c.Response.WriteAsJsonAsync(ApiFailure.Create(d.Code,d.Message,c.TraceIdentifier,d.Details));return;}if(ex is BadHttpRequestException or System.Text.Json.JsonException){c.Response.StatusCode=400;await c.Response.WriteAsJsonAsync(ApiFailure.Create("VALIDATION_ERROR","请求格式不正确。",c.TraceIdentifier));return;}app.Logger.LogError(ex,"Unhandled CreditService error; traceId={TraceId}",c.TraceIdentifier);c.Response.StatusCode=500;await c.Response.WriteAsJsonAsync(ApiFailure.Create("INTERNAL_ERROR","credits 服务暂时不可用。",c.TraceIdentifier));}));
app.Use(async(c,next)=>{if(c.Request.Path is "/healthz" or "/readyz"){await next();return;}if(c.Request.Headers["X-Gateway-Key"].Count!=1||!System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(System.Text.Encoding.UTF8.GetBytes(c.Request.Headers["X-Gateway-Key"]!),System.Text.Encoding.UTF8.GetBytes(gatewayKey))){c.Response.StatusCode=403;await c.Response.WriteAsJsonAsync(ApiFailure.Create("FORBIDDEN","该服务仅接受 Gateway 请求。",c.TraceIdentifier));return;}await next();});
app.MapGet("/healthz",()=>Results.Ok(new{status="live"}));app.MapGet("/readyz",()=>Results.Ok(new{status="ready",storage=provider}));
app.MapGet("/api/v1/credits/balance",async(HttpContext c,ISender sender,CancellationToken ct)=>Results.Ok(ApiSuccess.Create(await sender.Send(new GetBalanceQuery(User(c)),ct),c.TraceIdentifier)));
app.MapPost("/api/v1/credits/redemptions",async(RedeemRequest request,HttpContext c,ISender sender,CancellationToken ct)=>Results.Ok(ApiSuccess.Create(await sender.Send(new RedeemCodeCommand(User(c),request.Code??""),ct),c.TraceIdentifier)));
app.MapGet("/api/v1/admin/credit-codes",async(HttpContext c,ISender sender,CancellationToken ct)=>{Admin(c);return Results.Ok(ApiSuccess.Create(new{items=await sender.Send(new ListCodesQuery(),ct)},c.TraceIdentifier));});
app.MapPost("/api/v1/admin/credit-codes/batches",async(CreateBatchRequest request,HttpContext c,ISender sender,CancellationToken ct)=>{var admin=Admin(c);var items=await sender.Send(new CreateCodeBatchCommand(admin,request.Count??0,request.CreditsPerCode??0,request.ExpiresAt),ct);return Results.Json(ApiSuccess.Create(new{items},c.TraceIdentifier),statusCode:201);});
app.MapDelete("/api/v1/admin/credit-codes/{codeId:guid}",async(Guid codeId,HttpContext c,ISender sender,CancellationToken ct)=>{Admin(c);await sender.Send(new RevokeCodeCommand(codeId),ct);return Results.NoContent();});
app.MapPost("/internal/v1/credits/accounts",async(ProvisionRequest request,HttpContext c,ISender sender,CancellationToken ct)=>{Service(c,"AuthService");if(!request.UserId.HasValue)throw new CreditDomainException(400,"VALIDATION_ERROR","userId 必填。");return Results.Json(ApiSuccess.Create(await sender.Send(new ProvisionAccountCommand(request.UserId.Value),ct),c.TraceIdentifier),statusCode:201);});
app.MapDelete("/internal/v1/credits/accounts/{userId:guid}",async(Guid userId,HttpContext c,ISender sender,CancellationToken ct)=>{Service(c,"AuthService");await sender.Send(new DeleteAccountCommand(userId),ct);return Results.NoContent();});
app.MapPost("/internal/v1/credits/reservations",async(ReserveRequest request,HttpContext c,ISender sender,CancellationToken ct)=>{Service(c,"PracticeService","GalGameService");if(!request.UserId.HasValue||!request.OperationId.HasValue||!request.EstimatedTokenUnits.HasValue)throw new CreditDomainException(400,"VALIDATION_ERROR","预授权字段均为必填。");return Results.Json(ApiSuccess.Create(await sender.Send(new ReserveCreditsCommand(request.UserId.Value,request.OperationId.Value,request.OperationType??"",request.EstimatedTokenUnits.Value),ct),c.TraceIdentifier),statusCode:201);});
app.MapPost("/internal/v1/credits/reservations/{operationId:guid}/settlement",async(Guid operationId,SettleRequest request,HttpContext c,ISender sender,CancellationToken ct)=>{Service(c,"PracticeService","GalGameService");if(!request.ActualTokenUnits.HasValue)throw new CreditDomainException(400,"VALIDATION_ERROR","actualTokenUnits 必填。");return Results.Ok(ApiSuccess.Create(await sender.Send(new SettleCreditsCommand(operationId,request.ActualTokenUnits.Value),ct),c.TraceIdentifier));});
app.MapPost("/internal/v1/credits/reservations/{operationId:guid}/release",async(Guid operationId,HttpContext c,ISender sender,CancellationToken ct)=>{Service(c,"PracticeService","GalGameService");return Results.Ok(ApiSuccess.Create(await sender.Send(new ReleaseCreditsCommand(operationId),ct),c.TraceIdentifier));});
app.Run();
static Guid User(HttpContext c)=>Guid.TryParse(c.Request.Headers["X-User-Id"],out var id)?id:throw new CreditDomainException(401,"AUTH_REQUIRED","需要登录。");
static Guid Admin(HttpContext c){var id=User(c);return id==Guid.Parse("00000000-0000-4000-8000-000000000001")?id:throw new CreditDomainException(403,"FORBIDDEN","需要管理员权限。");}
static void Service(HttpContext c,params string[] allowed){var name=c.Request.Headers["X-Service-Name"].ToString();if(!allowed.Contains(name,StringComparer.Ordinal))throw new CreditDomainException(403,"FORBIDDEN","服务身份无权调用该接口。");}
public sealed record RedeemRequest(string? Code);public sealed record CreateBatchRequest(int? Count,decimal? CreditsPerCode,DateTimeOffset? ExpiresAt);public sealed record ProvisionRequest(Guid? UserId);public sealed record ReserveRequest(Guid? UserId,Guid? OperationId,string? OperationType,long? EstimatedTokenUnits);public sealed record SettleRequest(long? ActualTokenUnits);
public sealed record ApiError(string Code,string Message,object Details);public sealed record ApiSuccess(object Data,object Meta,string TraceId){public static ApiSuccess Create(object data,string trace)=>new(data,new{},trace);}public sealed record ApiFailure(object? Data,ApiError Error,string TraceId){public static ApiFailure Create(string code,string message,string trace,object? details=null)=>new(null,new(code,message,details??new{}),trace);}
public partial class Program { }
