using System.Security.Cryptography;
using CreditService.Application;
using CreditService.Domain;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using MySqlConnector;

namespace CreditService.Persistence;

public static class DependencyInjection
{
    public static IServiceCollection AddCreditPersistence(this IServiceCollection services, IConfiguration config)
    {
        var provider = config["CreditStore:Provider"] ?? "MySQL";
        if (string.Equals(provider, "Memory", StringComparison.OrdinalIgnoreCase)) return services.AddSingleton<ICreditRepository, MemoryCreditRepository>();
        var connection = config.GetConnectionString("CreditDatabase") ?? throw new InvalidOperationException("ConnectionStrings:CreditDatabase must be configured.");
        services.AddSingleton(new CreditDatabase(connection)); services.AddSingleton<ICreditRepository, MySqlCreditRepository>(); return services;
    }
}

public sealed class CreditDatabase(string connectionString)
{
    public MySqlConnection Open() { var c = new MySqlConnection(connectionString); c.Open(); return c; }
    public void EnsureCreated()
    {
        var b = new MySqlConnectionStringBuilder(connectionString); var database = b.Database;
        if (string.IsNullOrWhiteSpace(database) || !database.All(x => char.IsLetterOrDigit(x) || x == '_')) throw new InvalidOperationException("Invalid credit database name.");
        b.Database = ""; using (var server = new MySqlConnection(b.ConnectionString)) { server.Open(); using var q = server.CreateCommand(); q.CommandText = $"CREATE DATABASE IF NOT EXISTS `{database}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"; q.ExecuteNonQuery(); }
        using var c = Open(); using var command = c.CreateCommand(); command.CommandText = """
        CREATE TABLE IF NOT EXISTS credit_accounts(user_id CHAR(36) PRIMARY KEY,balance_units BIGINT NOT NULL,held_units BIGINT NOT NULL DEFAULT 0,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL);
        CREATE TABLE IF NOT EXISTS credit_redemption_codes(code_hash CHAR(64) PRIMARY KEY,code_id CHAR(36) NOT NULL UNIQUE,code_suffix VARCHAR(8) NOT NULL,credit_units BIGINT NOT NULL,status VARCHAR(16) NOT NULL,redeemed_by CHAR(36) NULL,redeemed_at DATETIME(6) NULL,expires_at DATETIME(6) NULL,created_at DATETIME(6) NOT NULL,created_by CHAR(36) NOT NULL,INDEX idx_credit_codes_created(created_at),INDEX idx_credit_codes_status(status));
        CREATE TABLE IF NOT EXISTS credit_reservations(operation_id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,operation_type VARCHAR(64) NOT NULL,estimated_units BIGINT NOT NULL,actual_units BIGINT NOT NULL DEFAULT 0,status VARCHAR(16) NOT NULL,created_at DATETIME(6) NOT NULL,updated_at DATETIME(6) NOT NULL,INDEX idx_credit_reservations_user(user_id));
        CREATE TABLE IF NOT EXISTS credit_ledger(entry_id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,operation_id CHAR(36) NULL,entry_type VARCHAR(32) NOT NULL,units BIGINT NOT NULL,balance_after_units BIGINT NOT NULL,created_at DATETIME(6) NOT NULL,INDEX idx_credit_ledger_user_created(user_id,created_at));
        """; command.ExecuteNonQuery();
    }
}

public sealed class MySqlCreditRepository(CreditDatabase database) : ICreditRepository
{
    public CreditAccount Provision(Guid userId)
    {
        using var c=database.Open(); using var tx=c.BeginTransaction(); using var q=c.CreateCommand(); q.Transaction=tx;
        q.CommandText="INSERT IGNORE INTO credit_accounts(user_id,balance_units,held_units,created_at,updated_at) VALUES(@user,@initial,0,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))"; q.Parameters.AddWithValue("@user",userId); q.Parameters.AddWithValue("@initial",CreditPolicy.InitialUnits); var inserted=q.ExecuteNonQuery();
        if(inserted==1){q.Parameters.Clear();q.CommandText="INSERT INTO credit_ledger(entry_id,user_id,operation_id,entry_type,units,balance_after_units,created_at) VALUES(@id,@user,NULL,'INITIAL_GRANT',@units,@units,UTC_TIMESTAMP(6))";q.Parameters.AddWithValue("@id",Guid.NewGuid());q.Parameters.AddWithValue("@user",userId);q.Parameters.AddWithValue("@units",CreditPolicy.InitialUnits);q.ExecuteNonQuery();}
        tx.Commit(); return GetAccount(userId)!;
    }
    public CreditAccount? GetAccount(Guid userId){using var c=database.Open();using var q=c.CreateCommand();q.CommandText="SELECT balance_units,held_units,created_at,updated_at FROM credit_accounts WHERE user_id=@user";q.Parameters.AddWithValue("@user",userId);using var r=q.ExecuteReader();return r.Read()?new(userId,r.GetInt64(0),r.GetInt64(1),Utc(r.GetDateTime(2)),Utc(r.GetDateTime(3))):null;}
    public void DeleteAccount(Guid userId){using var c=database.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="DELETE FROM credit_ledger WHERE user_id=@user;DELETE FROM credit_reservations WHERE user_id=@user;DELETE FROM credit_accounts WHERE user_id=@user";q.Parameters.AddWithValue("@user",userId);q.ExecuteNonQuery();tx.Commit();}
    public (CreditAccount Account, RedemptionCode Code) Redeem(Guid userId,string code)
    {
        var hash=Hash(code);using var c=database.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT credit_units,status,redeemed_by,redeemed_at,expires_at,created_at,created_by,code_suffix FROM credit_redemption_codes WHERE code_hash=@hash FOR UPDATE";q.Parameters.AddWithValue("@hash",hash);long units;DateTime? expires;Guid createdBy;DateTime created;string suffix;
        using(var r=q.ExecuteReader()){if(!r.Read())throw InvalidCode();units=r.GetInt64(0);var status=r.GetString(1);expires=r.IsDBNull(4)?null:r.GetDateTime(4);created=r.GetDateTime(5);createdBy=ReadGuid(r,6);suffix=r.GetString(7);if(status!="ACTIVE"||(expires is not null&&expires<=DateTime.UtcNow))throw InvalidCode();}
        q.Parameters.Clear();q.CommandText="UPDATE credit_redemption_codes SET status='REDEEMED',redeemed_by=@user,redeemed_at=UTC_TIMESTAMP(6) WHERE code_hash=@hash AND status='ACTIVE'";q.Parameters.AddWithValue("@user",userId);q.Parameters.AddWithValue("@hash",hash);if(q.ExecuteNonQuery()!=1)throw InvalidCode();
        q.Parameters.Clear();q.CommandText="UPDATE credit_accounts SET balance_units=balance_units+@units,updated_at=UTC_TIMESTAMP(6) WHERE user_id=@user";q.Parameters.AddWithValue("@units",units);q.Parameters.AddWithValue("@user",userId);if(q.ExecuteNonQuery()!=1)throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 账户不存在。");
        q.Parameters.Clear();q.CommandText="SELECT balance_units FROM credit_accounts WHERE user_id=@user";q.Parameters.AddWithValue("@user",userId);var balance=Convert.ToInt64(q.ExecuteScalar());
        Ledger(q,userId,null,"REDEMPTION",units,balance);tx.Commit();var account=GetAccount(userId)!;return(account,new(Guid.Empty,"****"+suffix,units,RedemptionCodeStatus.Redeemed,userId,DateTimeOffset.UtcNow,expires is null?null:Utc(expires.Value),Utc(created),createdBy));
    }
    public IReadOnlyList<RedemptionCode> ListCodes(){using var c=database.Open();using var q=c.CreateCommand();q.CommandText="SELECT code_id,code_suffix,credit_units,status,redeemed_by,redeemed_at,expires_at,created_at,created_by FROM credit_redemption_codes ORDER BY created_at DESC LIMIT 5000";using var r=q.ExecuteReader();var result=new List<RedemptionCode>();while(r.Read()){var status=Enum.Parse<RedemptionCodeStatus>(r.GetString(3),true);if(status==RedemptionCodeStatus.Active&&!r.IsDBNull(6)&&r.GetDateTime(6)<=DateTime.UtcNow)status=RedemptionCodeStatus.Expired;result.Add(new(ReadGuid(r,0),"****"+r.GetString(1),r.GetInt64(2),status,r.IsDBNull(4)?null:ReadGuid(r,4),r.IsDBNull(5)?null:Utc(r.GetDateTime(5)),r.IsDBNull(6)?null:Utc(r.GetDateTime(6)),Utc(r.GetDateTime(7)),ReadGuid(r,8)));}return result;}
    public IReadOnlyList<RedemptionCode> CreateCodes(Guid admin,int count,long units,DateTimeOffset? expires){using var c=database.Open();using var tx=c.BeginTransaction();var result=new List<RedemptionCode>();for(var i=0;i<count;i++){for(var attempt=0;attempt<5;attempt++){var code="QZ-"+Convert.ToHexString(RandomNumberGenerator.GetBytes(10));var codeId=Guid.NewGuid();try{using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO credit_redemption_codes(code_hash,code_id,code_suffix,credit_units,status,expires_at,created_at,created_by) VALUES(@hash,@codeId,@suffix,@units,'ACTIVE',@expires,UTC_TIMESTAMP(6),@admin)";q.Parameters.AddWithValue("@hash",Hash(code));q.Parameters.AddWithValue("@codeId",codeId);q.Parameters.AddWithValue("@suffix",code[^6..]);q.Parameters.AddWithValue("@units",units);q.Parameters.AddWithValue("@expires",expires?.UtcDateTime??(object)DBNull.Value);q.Parameters.AddWithValue("@admin",admin);q.ExecuteNonQuery();result.Add(new(codeId,code,units,RedemptionCodeStatus.Active,null,null,expires,DateTimeOffset.UtcNow,admin));break;}catch(MySqlException ex)when(ex.Number==1062&&attempt<4){}}}if(result.Count!=count)throw new CreditDomainException(503,"SERVICE_UNAVAILABLE","兑换码批量生成失败。");tx.Commit();return result;}
    public bool RevokeCode(Guid codeId){using var c=database.Open();using var q=c.CreateCommand();q.CommandText="UPDATE credit_redemption_codes SET status='REVOKED' WHERE code_id=@id AND status='ACTIVE'";q.Parameters.AddWithValue("@id",codeId);return q.ExecuteNonQuery()==1;}
    public CreditReservation Reserve(Guid user,Guid operation,string type,long estimate)
    {
        using var c=database.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="SELECT user_id,operation_type,estimated_units,actual_units,status,created_at,updated_at FROM credit_reservations WHERE operation_id=@op FOR UPDATE";q.Parameters.AddWithValue("@op",operation);using(var r=q.ExecuteReader()){if(r.Read()){var existing=ReadReservation(operation,r);if(existing.UserId!=user||existing.OperationType!=type||existing.EstimatedUnits!=estimate)throw new CreditDomainException(409,"IDEMPOTENCY_KEY_REUSED","operationId 已用于不同的 credits 预授权。");tx.Commit();return existing;}}
        q.Parameters.Clear();q.CommandText="SELECT balance_units,held_units FROM credit_accounts WHERE user_id=@user FOR UPDATE";q.Parameters.AddWithValue("@user",user);long balance,held;using(var r=q.ExecuteReader()){if(!r.Read())throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 账户不存在。");balance=r.GetInt64(0);held=r.GetInt64(1);}if(balance-held<estimate)throw new CreditDomainException(402,"CREDITS_INSUFFICIENT","credits 不足，需要先兑换 credits。",new{balance=CreditPolicy.ToCredits(balance-held),required=CreditPolicy.ToCredits(estimate),purchaseUrl="https://pay.ldxp.cn/shop/7CX09W5E"});
        q.Parameters.Clear();q.CommandText="UPDATE credit_accounts SET held_units=held_units+@estimate,updated_at=UTC_TIMESTAMP(6) WHERE user_id=@user";q.Parameters.AddWithValue("@estimate",estimate);q.Parameters.AddWithValue("@user",user);q.ExecuteNonQuery();q.Parameters.Clear();q.CommandText="INSERT INTO credit_reservations(operation_id,user_id,operation_type,estimated_units,actual_units,status,created_at,updated_at) VALUES(@op,@user,@type,@estimate,0,'HELD',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))";q.Parameters.AddWithValue("@op",operation);q.Parameters.AddWithValue("@user",user);q.Parameters.AddWithValue("@type",type);q.Parameters.AddWithValue("@estimate",estimate);q.ExecuteNonQuery();tx.Commit();return new(operation,user,type,estimate,0,ReservationStatus.Held,DateTimeOffset.UtcNow,DateTimeOffset.UtcNow);
    }
    public CreditReservation Settle(Guid operation,long actual)
    {
        using var c=database.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;var reservation=LockReservation(q,operation);if(reservation.Status==ReservationStatus.Settled){tx.Commit();return reservation;}if(reservation.Status!=ReservationStatus.Held)throw new CreditDomainException(409,"STATE_CONFLICT","credits 预授权已经释放。");
        q.Parameters.Clear();q.CommandText="SELECT balance_units,held_units FROM credit_accounts WHERE user_id=@user FOR UPDATE";q.Parameters.AddWithValue("@user",reservation.UserId);long balance,held;using(var r=q.ExecuteReader()){if(!r.Read())throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 账户不存在。");balance=r.GetInt64(0);held=r.GetInt64(1);}var otherHeld=held-reservation.EstimatedUnits;if(balance-otherHeld<actual)throw new CreditDomainException(409,"CREDIT_ESTIMATE_EXCEEDED","实际消耗超过预授权且余额不足，任务需要人工核对。",new{available=CreditPolicy.ToCredits(balance-otherHeld),actual=CreditPolicy.ToCredits(actual)});
        var next=balance-actual;q.Parameters.Clear();q.CommandText="UPDATE credit_accounts SET balance_units=@next,held_units=@other,updated_at=UTC_TIMESTAMP(6) WHERE user_id=@user";q.Parameters.AddWithValue("@next",next);q.Parameters.AddWithValue("@other",otherHeld);q.Parameters.AddWithValue("@user",reservation.UserId);q.ExecuteNonQuery();q.Parameters.Clear();q.CommandText="UPDATE credit_reservations SET actual_units=@actual,status='SETTLED',updated_at=UTC_TIMESTAMP(6) WHERE operation_id=@op";q.Parameters.AddWithValue("@actual",actual);q.Parameters.AddWithValue("@op",operation);q.ExecuteNonQuery();Ledger(q,reservation.UserId,operation,"GENERATION_CHARGE",-actual,next);tx.Commit();return reservation with{ActualUnits=actual,Status=ReservationStatus.Settled,UpdatedAt=DateTimeOffset.UtcNow};
    }
    public CreditReservation Release(Guid operation)
    {
        using var c=database.Open();using var tx=c.BeginTransaction();using var q=c.CreateCommand();q.Transaction=tx;var reservation=LockReservation(q,operation);if(reservation.Status!=ReservationStatus.Held){tx.Commit();return reservation;}q.Parameters.Clear();q.CommandText="UPDATE credit_accounts SET held_units=GREATEST(0,held_units-@held),updated_at=UTC_TIMESTAMP(6) WHERE user_id=@user";q.Parameters.AddWithValue("@held",reservation.EstimatedUnits);q.Parameters.AddWithValue("@user",reservation.UserId);q.ExecuteNonQuery();q.Parameters.Clear();q.CommandText="UPDATE credit_reservations SET status='RELEASED',updated_at=UTC_TIMESTAMP(6) WHERE operation_id=@op";q.Parameters.AddWithValue("@op",operation);q.ExecuteNonQuery();tx.Commit();return reservation with{Status=ReservationStatus.Released,UpdatedAt=DateTimeOffset.UtcNow};
    }
    private CreditReservation LockReservation(MySqlCommand q,Guid operation){q.CommandText="SELECT user_id,operation_type,estimated_units,actual_units,status,created_at,updated_at FROM credit_reservations WHERE operation_id=@op FOR UPDATE";q.Parameters.AddWithValue("@op",operation);using var r=q.ExecuteReader();if(!r.Read())throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 预授权不存在。");return ReadReservation(operation,r);}
    private static CreditReservation ReadReservation(Guid id,MySqlDataReader r)=>new(id,ReadGuid(r,0),r.GetString(1),r.GetInt64(2),r.GetInt64(3),Enum.Parse<ReservationStatus>(r.GetString(4),true),Utc(r.GetDateTime(5)),Utc(r.GetDateTime(6)));
    private static Guid ReadGuid(MySqlDataReader reader,int ordinal)=>reader.GetValue(ordinal) switch
    {
        Guid value=>value,
        string value=>Guid.Parse(value),
        byte[] value when value.Length==16=>new Guid(value),
        var value=>Guid.Parse(Convert.ToString(value,System.Globalization.CultureInfo.InvariantCulture)
            ?? throw new InvalidOperationException($"Column {ordinal} does not contain a UUID."))
    };
    private static void Ledger(MySqlCommand q,Guid user,Guid? op,string type,long units,long balance){q.Parameters.Clear();q.CommandText="INSERT INTO credit_ledger(entry_id,user_id,operation_id,entry_type,units,balance_after_units,created_at) VALUES(@id,@user,@op,@type,@units,@balance,UTC_TIMESTAMP(6))";q.Parameters.AddWithValue("@id",Guid.NewGuid());q.Parameters.AddWithValue("@user",user);q.Parameters.AddWithValue("@op",op??(object)DBNull.Value);q.Parameters.AddWithValue("@type",type);q.Parameters.AddWithValue("@units",units);q.Parameters.AddWithValue("@balance",balance);q.ExecuteNonQuery();}
    private static CreditDomainException InvalidCode()=>new(422,"REDEMPTION_CODE_UNAVAILABLE","兑换码无效、已使用、已撤销或已过期。");private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(value)));private static DateTimeOffset Utc(DateTime value)=>new(DateTime.SpecifyKind(value,DateTimeKind.Utc));
}

public sealed class MemoryCreditRepository : ICreditRepository
{
    private readonly object sync=new();private readonly Dictionary<Guid,CreditAccount> accounts=[];private readonly Dictionary<string,RedemptionCode> codes=new(StringComparer.OrdinalIgnoreCase);private readonly Dictionary<Guid,CreditReservation> reservations=[];
    public CreditAccount Provision(Guid user){lock(sync){if(!accounts.TryGetValue(user,out var a)){var now=DateTimeOffset.UtcNow;a=new(user,CreditPolicy.InitialUnits,0,now,now);accounts[user]=a;}return a;}}
    public CreditAccount? GetAccount(Guid user){lock(sync)return accounts.GetValueOrDefault(user);}
    public void DeleteAccount(Guid user){lock(sync){accounts.Remove(user);foreach(var id in reservations.Where(x=>x.Value.UserId==user).Select(x=>x.Key).ToArray())reservations.Remove(id);}}
    public (CreditAccount,RedemptionCode) Redeem(Guid user,string code){lock(sync){if(!codes.TryGetValue(code,out var value)||value.Status!=RedemptionCodeStatus.Active||(value.ExpiresAt is not null&&value.ExpiresAt<=DateTimeOffset.UtcNow))throw new CreditDomainException(422,"REDEMPTION_CODE_UNAVAILABLE","兑换码无效、已使用、已撤销或已过期。");var a=accounts.GetValueOrDefault(user)??throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 账户不存在。");var now=DateTimeOffset.UtcNow;value=value with{Status=RedemptionCodeStatus.Redeemed,RedeemedBy=user,RedeemedAt=now};codes[code]=value;a=a with{BalanceUnits=a.BalanceUnits+value.CreditUnits,UpdatedAt=now};accounts[user]=a;return(a,value);}}
    public IReadOnlyList<RedemptionCode> ListCodes(){lock(sync)return codes.Values.OrderByDescending(x=>x.CreatedAt).ToArray();}
    public IReadOnlyList<RedemptionCode> CreateCodes(Guid admin,int count,long units,DateTimeOffset? expires){lock(sync){var result=new List<RedemptionCode>();while(result.Count<count){var code="QZ-"+Convert.ToHexString(RandomNumberGenerator.GetBytes(10));if(codes.ContainsKey(code))continue;var value=new RedemptionCode(Guid.NewGuid(),code,units,RedemptionCodeStatus.Active,null,null,expires,DateTimeOffset.UtcNow,admin);codes[code]=value;result.Add(value);}return result;}}
    public bool RevokeCode(Guid codeId){lock(sync){var pair=codes.FirstOrDefault(x=>x.Value.CodeId==codeId);if(pair.Value is null||pair.Value.Status!=RedemptionCodeStatus.Active)return false;codes[pair.Key]=pair.Value with{Status=RedemptionCodeStatus.Revoked};return true;}}
    public CreditReservation Reserve(Guid user,Guid op,string type,long estimate){lock(sync){if(reservations.TryGetValue(op,out var old)){if(old.UserId!=user||old.OperationType!=type||old.EstimatedUnits!=estimate)throw new CreditDomainException(409,"IDEMPOTENCY_KEY_REUSED","operationId 已用于不同预授权。");return old;}var a=accounts.GetValueOrDefault(user)??throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 账户不存在。");if(a.AvailableUnits<estimate)throw new CreditDomainException(402,"CREDITS_INSUFFICIENT","credits 不足，需要先兑换 credits。",new{balance=CreditPolicy.ToCredits(a.AvailableUnits),required=CreditPolicy.ToCredits(estimate),purchaseUrl="https://pay.ldxp.cn/shop/7CX09W5E"});var now=DateTimeOffset.UtcNow;a=a with{HeldUnits=a.HeldUnits+estimate,UpdatedAt=now};accounts[user]=a;var r=new CreditReservation(op,user,type,estimate,0,ReservationStatus.Held,now,now);reservations[op]=r;return r;}}
    public CreditReservation Settle(Guid op,long actual){lock(sync){var r=reservations.GetValueOrDefault(op)??throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 预授权不存在。");if(r.Status==ReservationStatus.Settled)return r;if(r.Status!=ReservationStatus.Held)throw new CreditDomainException(409,"STATE_CONFLICT","credits 预授权已经释放。");var a=accounts[r.UserId];var other=a.HeldUnits-r.EstimatedUnits;if(a.BalanceUnits-other<actual)throw new CreditDomainException(409,"CREDIT_ESTIMATE_EXCEEDED","实际消耗超过预授权且余额不足。");var now=DateTimeOffset.UtcNow;accounts[r.UserId]=a with{BalanceUnits=a.BalanceUnits-actual,HeldUnits=other,UpdatedAt=now};r=r with{ActualUnits=actual,Status=ReservationStatus.Settled,UpdatedAt=now};reservations[op]=r;return r;}}
    public CreditReservation Release(Guid op){lock(sync){var r=reservations.GetValueOrDefault(op)??throw new CreditDomainException(404,"RESOURCE_NOT_FOUND","credits 预授权不存在。");if(r.Status!=ReservationStatus.Held)return r;var a=accounts[r.UserId];var now=DateTimeOffset.UtcNow;accounts[r.UserId]=a with{HeldUnits=Math.Max(0,a.HeldUnits-r.EstimatedUnits),UpdatedAt=now};r=r with{Status=ReservationStatus.Released,UpdatedAt=now};reservations[op]=r;return r;}}
}
